sudo: required
dist: trusty
language: python
python:
    - "2.7"
before_install:
    - pip install mkdocs
    - pip install mkdocs-bootswatch
install: true
script:
    - .travis/build.sh
deploy:
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
        branch: master
