site_name: "PDNS Manager"
copyright: CC-BY-SA Lukas Metzger
repo_url: "https://github.com/loewexy/pdns-manager"
theme_dir: "theme"
docs_dir: "content"
pages:
    - Home: "index.md"
    - Getting Started: "quickstart.md"
    - Download: "download.md"
    - About: "about.md"

