site_name: "PDNS Manager"
copyright: CC-BY-SA Lukas Metzger
repo_url: "https://github.com/loewexy/pdnsmanager"
theme:
    name: 'mkdocs'
    custom_dir: "theme/"
docs_dir: "content"
nav:
    - Home: "index.md"
    - Getting Started: "quickstart.md"
    - Documentation:
        - Add your first domain: "documentation/firstdomain.md"
        - Users: "documentation/users.md"
        - API: "documentation/api.md"
        - Let's Encrypt: "documentation/letsencrypt.md"
        - Configuration: "documentation/configuration.md"
        - Configuration - Authentication: "documentation/configuration_authentication.md"
        - Upgrading from v1: "documentation/upgrading-v1.md"
    - Download: "download.md"
    - About & Privacy: "about.md"

